language: python
python:  
  - "2.7"  
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
before_script:
  - ./init.sh
script:
  - "pep8 --exclude=*/migrations/ ."
  - python manage.py test
